database:
  driverClass : org.h2.Driver
  url: 'jdbc:h2:mem:db;DB_CLOSE_DELAY=-1'
  user: sa

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  # loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    # org.skife.jdbi.v2: TRACE